version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - GMAIL_USERNAME=${GMAIL_USERNAME}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_WEB_CORS_ALLOWED_ORIGINS=${FRONTEND_URL}
    networks:
      - kidsync-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${BACKEND_URL}
      - NODE_ENV=production
    networks:
      - kidsync-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:6.0 # Using MongoDB 6.0 as specified
    ports: # Expose port for connection from IDE
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=kidsync
    volumes:
      - mongo-data:/data/db
    networks:
      - kidsync-net

networks:
  kidsync-net:
    driver: bridge

volumes:
  mongo-data:  # backend-maven-repo: # No longer needed if backend isn't built in Docker
