version: '3.8'
services:
  # Backend service commented out - will run directly from IDE
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env
  #   environment:
  #     - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/kidsync
  #     - GMAIL_USERNAME=${GMAIL_USERNAME}
  #     - GMAIL_PASSWORD=${GMAIL_PASSWORD}
  #     - JWT_SECRET=${JWT_SECRET}
  #     - SERVER_PORT=8080 
  #   depends_on:
  #     - mongo
  #   networks:
  #     - kidsync-net
  #   volumes:
  #      - backend-maven-repo:/root/.m2 

  # Frontend service commented out for now
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - kidsync-net

  mongo:
    image: mongo:6.0 # Using MongoDB 6.0 as specified
    ports: # Expose port for connection from IDE
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=kidsync
    volumes:
      - mongo-data:/data/db
    networks:
      - kidsync-net

networks:
  kidsync-net:
    driver: bridge

volumes:
  mongo-data:
  # backend-maven-repo: # No longer needed if backend isn't built in Docker