services:
  - type: web
    name: kids-sync-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GMAIL_USERNAME
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_WEB_CORS_ALLOWED_ORIGINS
        value: https://kids-sync-app.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://kids-sync-app.onrender.com
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true 