# MongoDB Configuration
spring:
  # Active Profile
  profiles:
    active: prod

  data:
    mongodb:
      uri: ${MONGODB_URI}

  # CORS Configuration
  web:
    cors:
      allowed-origins: ${SPRING_WEB_CORS_ALLOWED_ORIGINS:http://localhost:3000}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}

# Logging Configuration
logging:
  level:
    com:
      arrayindex:
        kids_sync_app: DEBUG
    org:
      springframework:
        security: INFO

# Server Configuration
server:
  port: 8080